### ISSUE TITLE
How can I know if a job panicked?

### ISSUE THREAD

**Issue by pornel** [rust-threadpool/rust-threadpool#13]
If I execute a job, how can I know it has panicked? 

The example uses a channel to collect results, but I don't think it's possible to distinguish between a response that won't be sent, and a response that hasn't been sent _yet_.

``` rust
use threadpool::ThreadPool;
use std::sync::mpsc::channel;

let pool = ThreadPool::new(4);

let (tx, rx) = channel();
for i in 0..8 {
    let tx = tx.clone();
    pool.execute(move|| {
        if i == 4 {panic!();} // -- unexpected failure added here --
        tx.send(i).unwrap();
    });
}

// And now this code waits forever:
assert_eq!(rx.iter().take(8).fold(0, |a, b| a + b), 28);
```

**Comment by frewsxcv** [comment]
@pornel What do you think about https://github.com/frewsxcv/rust-threadpool/pull/31 ?

**Comment by pornel** [comment]
I don't see how it solves the problem of iterator being stuck forever.

It would work for me if `rx.iter()` returned `Result`s with errors for panicked threads. Or if there was `pool.execute().or_else(||)` callback to let me provide the error value.

For now in my code I use a dummy object with `Drop` that sends back `Err` when thread is unwinding.

**Comment by aidanhs** [comment]
Sorry, I just skimmed this issue and all I took away was "If I execute a job, how can I know it has panicked?", which the PR solves as long as you're polling (which I am).

A different solution would be necessary for the iteration example.

**Comment by frewsxcv** [comment]
I just merged https://github.com/frewsxcv/rust-threadpool/issues/31, but I'll leave this open as there's still room for improvement.

**Comment by frewsxcv** [comment]
`catch_unwind` is now stable, which might make this easier to implement?

http://blog.rust-lang.org/2016/05/26/Rust-1.9.html

**Comment by dns2utf8** [comment]
The solution is to reduce the lifetime of `tx`:

```rust
extern crate threadpool;

use threadpool::ThreadPool;
use std::sync::mpsc::channel;

fn main() {
  let pool = ThreadPool::new(4);

  let rx = {
    let (tx, rx) = channel();
    for i in 0..8 {
        let tx = tx.clone();
        pool.execute(move|| {
            if i == 4 {panic!();} // -- unexpected failure added here --
            tx.send(i).unwrap();
        });
    }
    rx
  };

  // And now this code waits for all the senders to be destructed:
  assert_eq!(rx.iter().take(8).fold(0, |a, b| a + b), 24);
}
```

because the iter of `rx` will stop as soon as there are no more senders and `take` only iterates over the first `n? iterations of `iter`.

This works because `iter` returns an iterator that will block waiting for messages, but never `panic!`. It will return `None` when the channel has hung up.

The final `None` will cause the fold to terminate, so it correctly calculates all the values exept the 4.


Maybe we could add this to the examples, what do you think?

**Comment by frewsxcv** [comment]
`join` is now a method on `ThreadPool` to wait until all jobs have finished:

https://docs.rs/threadpool/1.6.0/threadpool/struct.ThreadPool.html#method.join

It seems like one can call `join` and then check the `panic_count` of the `ThreadPool` to see if there were any panics. Is it fair to say this issue is solved now?

**Comment by pornel** [comment]
Thanks
